site:
  title: SUSE® Rancher Manager
  url: /
  start_page: latest@rancher-manager:en:about-rancher/what-is-rancher.adoc
  robots: disallow
content:
  sources: 
  - url: https://github.com/rancher/rancher-product-docs
    branches: [main]
    start_paths: [shared, versions/latest, versions/v2.12, versions/v2.11, versions/v2.10, versions/v2.9, versions/v2.8]
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher
asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, zh]
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true
