name: Test deployment

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  test-deploy:
    uses: btat/product-docs-common/.github/workflows/test-deploy-min.yml@workflow-run
