name: Test Community deployment
run-name: Test Community deployment 

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - '*-maintenance'
      - 'release-notes-*'
    paths-ignore:
      - '**/README.md'

permissions:
  pull-requests: write

jobs:
  test-deploy:
    uses: btat/product-docs-common/.github/workflows/test-deploy-min.yml@8f21f75bd36bb7c7658d9713e733312c82b4fffb # main
    secrets:
      token: ${{ github.token }}
    with:
      playbook-name: 'playbook-community-local.yml'
